name: colbert
backbone_name: bert-base-uncased
override_backbone_name: Null
ckpt_path: Null
out_dim: 128
# Quantization
is_use_quantization: False
quantization_bit: 8
is_use_lora: False
# ideas
is_use_q_weight: False
is_use_d_weight: False
# Loss coefficient
inter_loss_coeff: 1.0
intra_loss_coeff: 1.0