name: eagle
backbone_name: bert-base-uncased
override_backbone_name: Null
ckpt_path: Null
out_dim: 128
# Quantization
is_use_quantization: False
quantization_bit: 8
is_use_lora: False
# ideas
is_use_q_weight: True
is_use_d_weight: True
sim_type: combination
# sim_type: inner_agg
# sim_type: outer_agg
w_regularize_strategy: l1
# Loss coefficient
inter_loss_coeff: 1.0
intra_loss_coeff: 1.0
q_weight_coeff: 0.01
d_weight_coeff: 0.0000005
# q_weight_strategy: sigmoid
q_weight_strategy: relu
# q_weight_strategy: attention
# d_weight_strategy: sigmoid
d_weight_strategy: relu
# d_weight_strategy: attention
reduce_strategy: mean
# reduce_strategy: max
# reduce_strategy: min
use_multi_doc_granularity: False