_global:
    is_debug: False
    seed: 10
    nway: 32
    tag: "default"
    root_dir: "/root/EAGLE/runs"
defaults:
    - model: eagle
    - tokenizers: default
    - dataset: default
    - training: default
    - indexing: default