name: beir-msmarco
dir_path: /root/EAGLE/data/
corpus_file: corpus.jsonl
data_cache_file: dataset.cache.lz4
query_file: queries.jsonl
d_word_range_file: word_indices.doc.pkl
d_phrase_range_file: phrase_indices.doc.pkl
q_word_range_file: word_indices.query.pkl
q_phrase_range_file: phrase_indices.query.pkl
train_contrastive:
    # For debugging
    sample_size: -1
    debug_sample_size: 1000
    negative_start_offset: 50
    nway: 32
    data_file: train.jsonl
    qrel_file: qrels/train.tsv
train_distillation:
    # For debugging
    sample_size: -1
    debug_sample_size: 1000
    negative_start_offset: 0
    nway: 32
    data_file: train_distillation_filtered.jsonl
    qrel_file: qrels/train_distillation_filtered.tsv
val:
    sample_size: -1
    debug_sample_size: 200
    negative_start_offset: 0
    nway: 100
    data_file: dev.jsonl